<x-layouts.guest title="Tentang Kasiva — POS untuk Profit Outlet" description="Kenali misi Kasiva dalam membantu bisnis F&B dan retail Indonesia mengelola transaksi, HPP, stok, dan profit.">
<div class="min-h-dvh bg-[var(--app-bg)] text-[var(--text-main)]">
<header class="sticky top-0 z-40 border-b border-[var(--border-color)] bg-[var(--header-bg)] backdrop-blur-xl"><div class="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 md:px-8"><a href="{{ route('landing') }}" class="ks-focus flex min-h-11 items-center gap-2.5 rounded-xl"><img src="{{ asset('images/kasiva-logo-icon-128.png') }}" alt="" class="h-9 w-9 rounded-xl bg-white p-1"><span class="font-black">Kasiva</span></a><div class="flex gap-2"><button onclick="window.toggleKasivaTheme()" class="ks-focus flex h-11 w-11 items-center justify-center rounded-xl border border-[var(--border-color)] bg-[var(--card-sub-bg)]" aria-label="Ganti tema"><x-icon name="sun" class="hidden h-4 w-4 dark:block"/><x-icon name="moon" class="h-4 w-4 dark:hidden"/></button><a href="{{ route('register') }}" class="ks-btn-primary">Mulai gratis</a></div></div></header>
<main><section class="relative overflow-hidden border-b border-[var(--border-color)] px-4 py-20 text-center md:py-28"><div class="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_20%,rgb(0_170_166_/_0.18),transparent_38%)]"></div><div class="relative mx-auto max-w-4xl"><p class="ks-eyebrow">Tentang Kasiva</p><h1 class="mt-4 text-4xl font-black leading-tight tracking-tight md:text-6xl">Kami percaya angka bisnis harus <span class="text-[#00AAA6]">mudah dipahami.</span></h1><p class="ks-muted mx-auto mt-6 max-w-2xl text-base leading-8">Kasiva dibangun untuk membantu pemilik F&amp;B dan retail melihat hubungan antara transaksi, bahan baku, biaya operasional, dan profit—tanpa spreadsheet yang melelahkan.</p></div></section>
<section class="mx-auto max-w-6xl px-4 py-16 md:px-8 md:py-24"><div class="grid gap-5 md:grid-cols-3">@foreach([['shield','Misi','Membantu outlet bekerja lebih tertib melalui data transaksi dan biaya yang dapat dipercaya.'],['chart-bar','Visi','Menjadi fondasi operasional yang relevan bagi bisnis Indonesia dari satu outlet hingga jaringan.'],['sparkles','Prinsip','Sederhana saat dipakai, transparan saat menghitung, dan aman saat menyimpan data.']] as $item)<article class="ks-card p-7"><span class="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#00AAA6]/15 text-[#00AAA6]"><x-icon name="{{ $item[0] }}" class="h-6 w-6"/></span><h2 class="mt-5 text-xl font-black">{{ $item[1] }}</h2><p class="ks-muted mt-3 text-sm leading-7">{{ $item[2] }}</p></article>@endforeach</div></section>
<section class="border-y border-[var(--border-color)] bg-[var(--card-sub-bg)]"><div class="mx-auto grid max-w-6xl items-center gap-12 px-4 py-16 md:px-8 md:py-24 lg:grid-cols-2"><div><p class="ks-eyebrow">Mengapa Kasiva</p><h2 class="mt-4 text-3xl font-black md:text-5xl">Profit tidak boleh sekadar sisa kas.</h2><p class="ks-muted mt-5 leading-8">Omzet yang besar belum tentu berarti bisnis sehat. Karena itu Kasiva menghubungkan harga beli, resep, stok, transaksi, platform delivery, dan pengeluaran dalam satu alur.</p></div><div class="space-y-3">@foreach([['package','HPP mengikuti pergerakan harga bahan'],['store','Kasir tetap cepat saat antrean ramai'],['refresh','Operasional tetap berjalan ketika offline'],['gift','Loyalitas terhubung langsung ke transaksi'],['shield','Akses staf dibatasi sesuai tanggung jawab']] as $point)<div class="ks-card flex items-center gap-4 p-4"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#8696ED]/15 text-[#8696ED]"><x-icon name="{{ $point[0] }}" class="h-5 w-5"/></span><p class="text-sm font-extrabold">{{ $point[1] }}</p></div>@endforeach</div></div></section>
<section class="px-4 py-16 md:px-8 md:py-24"><div class="mx-auto max-w-5xl rounded-[32px] bg-[#272D48] px-6 py-14 text-center text-white md:p-16"><p class="text-xs font-black uppercase tracking-[.2em] text-[#3EDAD7]">Mulai dengan fondasi yang lebih sehat</p><h2 class="mt-4 text-3xl font-black md:text-5xl">Kelola outlet dengan angka yang jelas.</h2><p class="mx-auto mt-5 max-w-xl text-sm leading-7 text-slate-300">Coba Kasiva untuk transaksi, stok, loyalitas, dan laporan profit outlet Anda.</p><a href="{{ route('register') }}" class="ks-btn-primary mt-7">Daftar outlet gratis <x-icon name="arrow-right" class="h-4 w-4"/></a></div></section></main>
<footer class="border-t border-[var(--border-color)]"><div class="mx-auto flex max-w-6xl flex-col justify-between gap-4 px-4 py-8 text-xs md:flex-row md:px-8"><p class="ks-muted">© {{ date('Y') }} Kasiva POS.</p><nav class="flex flex-wrap gap-5 font-bold"><a href="{{ route('about') }}" aria-current="page" class="text-[#00AAA6]">Tentang</a><a href="{{ route('privacy') }}">Privasi</a><a href="{{ route('terms') }}">Ketentuan</a></nav></div></footer>
</div>
</x-layouts.guest>