<x-layouts.guest title="Kebijakan Privasi — Kasiva POS" description="Pelajari bagaimana Kasiva melindungi data transaksi, resep, pelanggan, dan akun outlet Anda.">
<div class="min-h-dvh bg-[var(--app-bg)] text-[var(--text-main)]">
    <header class="sticky top-0 z-40 border-b border-[var(--border-color)] bg-[var(--header-bg)] backdrop-blur-xl"><div class="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 md:px-8"><a href="{{ route('landing') }}" class="ks-focus flex min-h-11 items-center gap-2.5 rounded-xl"><img src="{{ asset('images/kasiva-logo-icon-128.png') }}" alt="" class="h-9 w-9 rounded-xl bg-white p-1"><span class="font-black">Kasiva</span></a><div class="flex gap-2"><button onclick="window.toggleKasivaTheme()" class="ks-focus flex h-11 w-11 items-center justify-center rounded-xl border border-[var(--border-color)] bg-[var(--card-sub-bg)]" aria-label="Ganti tema"><x-icon name="sun" class="hidden h-4 w-4 dark:block"/><x-icon name="moon" class="h-4 w-4 dark:hidden"/></button><a href="{{ route('register') }}" class="ks-btn-primary">Mulai gratis</a></div></div></header>
    <main id="main-content"><section class="border-b border-[var(--border-color)] px-4 py-16 text-center md:py-24"><p class="ks-eyebrow">Legal dan keamanan</p><h1 class="mx-auto mt-4 max-w-3xl text-4xl font-black tracking-tight md:text-6xl">Kebijakan Privasi</h1><p class="ks-muted mx-auto mt-5 max-w-2xl leading-7">Cara Kasiva mengelola dan melindungi data usaha, transaksi, resep, serta pelanggan Anda.</p><p class="ks-muted mt-4 text-xs">Terakhir diperbarui: 25 April 2026</p></section>
    <article class="mx-auto max-w-3xl space-y-8 px-4 py-12 md:px-8 md:py-16"><div class="ks-card p-6 text-sm leading-7 sm:p-8">Kasiva POS memprioritaskan kerahasiaan dan keamanan data transaksi finansial, takaran resep HPP, serta data pelanggan Anda. Dokumen ini menjelaskan data yang dikelola, tujuan penggunaannya, dan kontrol yang tersedia bagi pemilik outlet.</div>
    @foreach([
      ['database','1. Pengumpulan dan kepemilikan data',['Data penjualan dan katalog hanya dapat diakses oleh akun outlet yang berwenang.','Data keuangan, resep HPP, dan margin merupakan milik pemilik usaha.','Kasiva tidak menjual data transaksi Anda kepada pihak ketiga.']],
      ['eye','2. Tujuan penggunaan informasi',['Memproses transaksi, pemotongan stok bahan, dan pembuatan struk.','Menyusun laporan omzet, HPP, laba, dan performa outlet.','Mengelola member, stempel loyalitas, dan promo yang Anda aktifkan.']],
      ['shield','3. Keamanan akun dan transmisi',['Kata sandi dan PIN disimpan dalam bentuk hash standar industri.','Koneksi produksi harus menggunakan HTTPS/TLS.','Hak akses staf dibatasi melalui role dan permission.']],
      ['server','4. Penyimpanan dan sinkronisasi',['Fitur offline menyimpan data tertentu pada perangkat untuk menjaga operasional.','Antrean perubahan disinkronkan saat koneksi tersedia.','Akses fisik ke perangkat tetap menjadi tanggung jawab outlet.']],
      ['users','5. Hak dan tanggung jawab pengguna',['Pemilik dapat memperbarui data akun dan outlet melalui pengaturan.','Permintaan terkait data dapat dikirim ke alamat kontak resmi.','Pengguna wajib menjaga kredensial dan mencabut akses staf yang tidak lagi bekerja.']],
    ] as $section)<section aria-labelledby="privacy-{{ $loop->iteration }}"><div class="flex items-center gap-3"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#00AAA6]/15 text-[#00AAA6]"><x-icon name="{{ $section[0] }}" class="h-5 w-5"/></span><h2 id="privacy-{{ $loop->iteration }}" class="text-xl font-black">{{ $section[1] }}</h2></div><ul class="ks-card mt-4 space-y-3 p-6 text-sm leading-7 sm:p-7">@foreach($section[2] as $item)<li class="flex gap-3"><x-icon name="check" class="mt-1.5 h-4 w-4 shrink-0 text-[#00AAA6]"/><span class="ks-muted">{{ $item }}</span></li>@endforeach</ul></section>@endforeach
    <section class="rounded-3xl border border-[#00AAA6]/30 bg-[#00AAA6]/10 p-7 text-center"><h2 class="text-xl font-black">Pertanyaan tentang privasi?</h2><p class="ks-muted mt-2 text-sm">Hubungi tim Kasiva untuk permintaan atau klarifikasi terkait data.</p><a href="mailto:privacy@kasiva.id" class="ks-btn-primary mt-5">privacy@kasiva.id</a></section></article></main>
    <footer class="border-t border-[var(--border-color)]"><div class="mx-auto flex max-w-6xl flex-col justify-between gap-4 px-4 py-8 text-xs md:flex-row md:px-8"><p class="ks-muted">© {{ date('Y') }} Kasiva POS.</p><nav class="flex flex-wrap gap-5 font-bold"><a href="{{ route('about') }}">Tentang</a><a href="{{ route('privacy') }}" aria-current="page" class="text-[#00AAA6]">Privasi</a><a href="{{ route('terms') }}">Ketentuan</a></nav></div></footer>
</div>
</x-layouts.guest>