<x-layouts.guest title="Syarat dan Ketentuan — Kasiva POS" description="Syarat penggunaan layanan Kasiva POS untuk pemilik outlet dan staf.">
<div class="min-h-dvh bg-[var(--app-bg)] text-[var(--text-main)]">
<header class="sticky top-0 z-40 border-b border-[var(--border-color)] bg-[var(--header-bg)] backdrop-blur-xl"><div class="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 md:px-8"><a href="{{ route('landing') }}" class="ks-focus flex min-h-11 items-center gap-2.5 rounded-xl"><img src="{{ asset('images/kasiva-logo-icon-128.png') }}" alt="" class="h-9 w-9 rounded-xl bg-white p-1"><span class="font-black">Kasiva</span></a><div class="flex gap-2"><button onclick="window.toggleKasivaTheme()" class="ks-focus flex h-11 w-11 items-center justify-center rounded-xl border border-[var(--border-color)] bg-[var(--card-sub-bg)]" aria-label="Ganti tema"><x-icon name="sun" class="hidden h-4 w-4 dark:block"/><x-icon name="moon" class="h-4 w-4 dark:hidden"/></button><a href="{{ route('register') }}" class="ks-btn-primary">Mulai gratis</a></div></div></header>
<main><section class="border-b border-[var(--border-color)] px-4 py-16 text-center md:py-24"><p class="ks-eyebrow">Kesepakatan layanan</p><h1 class="mx-auto mt-4 max-w-3xl text-4xl font-black tracking-tight md:text-6xl">Syarat dan Ketentuan</h1><p class="ks-muted mx-auto mt-5 max-w-2xl leading-7">Ketentuan dasar penggunaan Kasiva POS oleh pemilik outlet, manajer, dan staf.</p><p class="ks-muted mt-4 text-xs">Terakhir diperbarui: 25 April 2026</p></section>
<article class="mx-auto max-w-3xl space-y-8 px-4 py-12 md:px-8 md:py-16"><div class="ks-card p-6 text-sm leading-7 sm:p-8">Dengan mendaftar, masuk, atau menggunakan Kasiva POS, Anda menyatakan telah membaca dan menyetujui ketentuan berikut. Pemilik akun bertanggung jawab memastikan staf yang diberi akses memahami penggunaan sistem.</div>
@foreach([
['shield','1. Penerimaan syarat','Penggunaan aplikasi berarti Anda menerima ketentuan ini serta kebijakan privasi yang berlaku. Jika tidak menyetujuinya, hentikan penggunaan layanan.'],
['store','2. Cakupan layanan POS','Kasiva menyediakan pencatatan transaksi, katalog, resep dan HPP, inventaris, pembayaran, loyalitas, pengeluaran, serta laporan. Fitur dapat berkembang selama fase early access.'],
['users','3. Akun dan keamanan','Pemilik bertanggung jawab atas kredensial akun, PIN staf, role, dan permission. Aktivitas yang dilakukan melalui akun terautentikasi dianggap sebagai aktivitas outlet.'],
['info','4. Penggunaan yang dilarang','Kasiva tidak boleh dipakai untuk transaksi ilegal, pencucian uang, akses tanpa izin, manipulasi berbahaya, atau tindakan yang mengganggu layanan dan pengguna lain.'],
['refresh','5. Mode offline dan sinkronisasi','Fitur offline membantu menjaga transaksi saat koneksi terganggu. Outlet bertanggung jawab memastikan perangkat aman dan melakukan sinkronisasi ketika jaringan kembali tersedia.'],
['chart-bar','6. Akurasi data bisnis','Laporan bergantung pada akurasi katalog, resep, harga beli, transaksi, dan pengeluaran yang dimasukkan pengguna. Kasiva membantu perhitungan, tetapi keputusan bisnis tetap menjadi tanggung jawab pemilik.'],
['sparkles','7. Perubahan layanan','Ketentuan atau paket layanan dapat diperbarui. Perubahan material akan diinformasikan secara wajar sebelum berlaku.'],
] as $section)<section class="ks-card p-6 sm:p-7" aria-labelledby="terms-{{ $loop->iteration }}"><div class="flex items-start gap-3"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#8696ED]/15 text-[#8696ED]"><x-icon name="{{ $section[0] }}" class="h-5 w-5"/></span><div><h2 id="terms-{{ $loop->iteration }}" class="text-lg font-black">{{ $section[1] }}</h2><p class="ks-muted mt-2 text-sm leading-7">{{ $section[2] }}</p></div></div></section>@endforeach
<section class="rounded-3xl border border-[#00AAA6]/30 bg-[#00AAA6]/10 p-7 text-center"><h2 class="text-xl font-black">Butuh klarifikasi?</h2><p class="ks-muted mt-2 text-sm">Tim kami siap menjelaskan ketentuan penggunaan.</p><a href="mailto:support@kasiva.id" class="ks-btn-primary mt-5">support@kasiva.id</a></section></article></main>
<footer class="border-t border-[var(--border-color)]"><div class="mx-auto flex max-w-6xl flex-col justify-between gap-4 px-4 py-8 text-xs md:flex-row md:px-8"><p class="ks-muted">© {{ date('Y') }} Kasiva POS.</p><nav class="flex flex-wrap gap-5 font-bold"><a href="{{ route('about') }}">Tentang</a><a href="{{ route('privacy') }}">Privasi</a><a href="{{ route('terms') }}" aria-current="page" class="text-[#00AAA6]">Ketentuan</a></nav></div></footer>
</div>
</x-layouts.guest>