<div class="space-y-6">
<section class="ks-card relative overflow-hidden p-6 md:p-8"><div class="pointer-events-none absolute -right-16 -top-20 h-56 w-56 rounded-full bg-[#00AAA6]/10 blur-3xl"></div><div class="relative flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p class="ks-eyebrow">Inventaris dan HPP</p><h1 class="mt-2 text-2xl font-black md:text-3xl">Manajemen Inventaris &amp; Menu</h1><p class="ks-muted mt-2 max-w-2xl text-sm leading-6">Kelola katalog, resep per porsi, stok bahan, kategori, dan varian.</p></div><div class="flex flex-col gap-2 sm:flex-row"><a href="{{ route('settings.products') }}" class="ks-btn-primary"><x-icon name="plus" class="h-4 w-4"/>Tambah menu</a><a href="{{ route('inventory.materials') }}" class="ks-btn-secondary"><x-icon name="package" class="h-4 w-4 text-[#00AAA6]"/>Restok bahan</a></div></div></section>
<section aria-label="Ringkasan inventaris" class="grid grid-cols-2 gap-3 md:grid-cols-4">@foreach([
['Produk aktif',$totalProducts,'Menu',''],['Bahan baku',$totalMaterials,'Item',''],['Stok menipis',$lowStockMaterials,'Bahan',$lowStockMaterials > 0 ? 'text-amber-500' : 'text-emerald-500'],['Kategori / varian',$totalCategories,$totalVariants.' varian','text-[#00AAA6]']
] as $metric)<div class="ks-card p-5"><p class="ks-muted text-[10px] font-extrabold uppercase tracking-wider">{{ $metric[0] }}</p><p class="mt-2 text-2xl font-black {{ $metric[3] }}">{{ $metric[1] }} <span class="ks-muted text-xs font-semibold">{{ $metric[2] }}</span></p></div>@endforeach</section>
<section aria-labelledby="inventory-modules"><h2 id="inventory-modules" class="mb-4 text-base font-black">Kelola inventaris</h2><div class="grid gap-4 md:grid-cols-2">
@foreach([
['settings.products','shopping-bag','Katalog Menu & Resep HPP','Harga jual, takaran resep, margin, dan foto produk.',$totalProducts.' menu'],
['inventory.materials','package','Bahan Baku & Restok','Stok, pembelian supplier, dan moving average HPP.',$totalMaterials.' bahan'],
['inventory.categories','tag','Kategori Menu','Ikon, pengelompokan, dan urutan kategori di kasir.',$totalCategories.' kategori'],
['inventory.variations','split','Varian & Opsi','Ukuran, level manis, suhu, dan tambahan harga.',$totalVariants.' grup varian'],
] as $item)<a href="{{ route($item[0]) }}" class="ks-card ks-focus group flex min-h-40 items-start gap-4 p-5 transition hover:-translate-y-0.5 hover:border-[#00AAA6]"><span class="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border border-[#00AAA6]/25 bg-[#00AAA6]/10 text-[#00AAA6]"><x-icon name="{{ $item[1] }}" class="h-6 w-6"/></span><span class="min-w-0 flex-1"><span class="flex items-center justify-between gap-3"><strong class="text-sm font-black">{{ $item[2] }}</strong><x-icon name="chevron-right" class="h-4 w-4 shrink-0 text-[var(--text-muted)] transition group-hover:translate-x-0.5 group-hover:text-[#00AAA6]"/></span><span class="ks-muted mt-2 block text-xs leading-5">{{ $item[3] }}</span><span class="mt-3 inline-flex rounded-full border border-[var(--border-color)] bg-[var(--card-sub-bg)] px-2.5 py-1 text-[10px] font-extrabold">{{ $item[4] }}</span></span></a>@endforeach
</div></section>
</div>
